---
output: html_document
editor_options: 
 chunk_output_type: console
---

# Get and save area targets data

## Setup

```{r}
#| label: setup
#| output: false

source(here::here("R", "libraries.R"))

source(here::here("R", "system_specific_constants.R"))
source(here::here("R", "constants.R"))

source(here::here("R", "functions.R"))

phase4_statecds <- c("AK00", "DE00", "ID01", "ID02", "ME02", "MT00", "ND00", "PA08", "SD00", "WY00")

```


## Prepare target files

Get all targets prepared

```{r}
#| label: targets-all
#| eval: false
#| output: false

# WEIGHTSDIR
# dir_ls(WEIGHTSDIR)
dir_ls(CDINTERMEDIATE) # we want cdbasefile_enhanced.csv

targets_data <- read_csv(fs::path(CDINTERMEDIATE, "cdbasefile_enhanced.csv"))
glimpse(targets_data)
count(targets_data, agistub, agilo, agihi, agirange)

saveRDS(targets_data, here::here("temp_data", "targets_data.rds")) # about 9 mb

```


Get targets used in the optimization

```{r}
#| label: targets-used
#| eval: false
#| output: false

# we need to put agistub on the target files

agibins <- read_csv(fs::path(CDINTERMEDIATE, "cd_agi_bins.csv"))
targetfiles <- dir_ls(WEIGHTSDIR) |> str_subset("targets.csv")

targets_used1 <- vroom(targetfiles, id="statecd") |> 
  mutate(statecd=path_file(statecd) |> str_sub(1, 4)) |> 
  mutate(active=!(str_sub(varname, 1, 1) == "#"),
         varname = ifelse(!active, 
                          varname |> str_remove("#") |> str_trim(),
                          varname)) 

targets_used2 <- targets_used1 |> 
  left_join(agibins |> 
              rename(agistub=AGI_STUB),
            by = join_by(agilo, agihi))

glimpse(targets_used2)
count(targets_used2, statecd)
count(targets_used2, active)
count(targets_used2, varname)
count(targets_used2, varname, active)
count(targets_used2, agistub, agilo, agihi, agirange)

saveRDS(targets_used2, here::here("temp_data", "targets_used.rds"))

targets_used <- readRDS(here::here("temp_data", "targets_used.rds"))

targets_used |> filter(statecd == "ak00")
targets_used |> filter(statecd == "de00")

rm(targets_used1, targets_used2)

```

