---
output: html_document
editor_options: 
 chunk_output_type: console
---

# Create mapping of tax calculator vars to soi vars

We do this in its own qmd file to make it easy to find, because it is also used in the examine project.

## Setup 
```{r}
#| label: setup

source(here::here("R", "libraries.R"))
source(here::here("R", "constants.R"))

# 334283385.27000004 national pop


```

## Create and save the mapping

```{r}
#| label: create-save-variable-mapping

# the MARS mappings let us get counts by filing status by agi range

# vmap <- read_csv(file="
# tcvar, soivar
# XTOT, XTOT
# c00100, MARS1
# c00100, MARS2
# c00100, MARS4
# c00100, v00100
# e00200, v00200
# e00300, v00300
# e01700, v01700
# e26270, v26270
# ")

# CAUTION: double-check that the MARS mappings work as intended in prepare

vmap <- read_csv(file="
varname, basevname, description
XTOT, XTOT, population
c00100, MARS1, fstatus == 1
c00100, MARS2, fstatus == 2
c00100, MARS4, fstatus == 3
c00100, v00100, agi
e00200, v00200, wages
e00300, v00300, interest income
e01700, v01700, pensions and annuities (taxable amount)
e26270, v26270, partnership and S corporation net income
e18400, v18425, state and local income or sales taxes allocated by S and L income taxes
e18500, v18500, state and local real estate taxes
", show_col_types = FALSE)

write_csv(vmap, fs::path(CDINTERMEDIATE, "cd_variable_mapping.csv"))

```

