---
output: html_document
editor_options: 
 chunk_output_type: console
---

# Download Congressional District data and documentation files

NOTE: To download data, change eval: to true in the header of the downloads chunk. Otherwise, this program assumes data already have been downloaded.

## Setup

```{r}
#| label: setup

source(here::here("R", "libraries.R"))
source(here::here("R", "constants.R"))

```


## Download CD data and documentation if not already downloaded

-   [SOI Congressional Districts landing page](https://www.irs.gov/statistics/soi-tax-stats-data-by-congressional-district)

    -   [2021 folder](https://www.irs.gov/statistics/soi-tax-stats-data-by-congressional-district-2021)


```{r}
#| label: downloads
#| eval: false

# data
fname <- fs::path_file(CDZIPURL)
download.file(url = CDZIPURL, destfile = fs::path(CDRAW, fname), mode = "wb")

# documentation
fname <- fs::path_file(CDDOCURL)
download.file(url = CDDOCURL, destfile = fs::path(CDRAW, fname), mode = "wb")

```


