---
output: html_document
editor_options: 
 chunk_output_type: console
---



# About the data

## IRS documentation

The following comments are extracted from the IRS SOI data documentation (21incddocguide.docx). All text in this section is a direct quote from the documentation.

### Time period

The Statistics of Income (SOI) Division’s Congressional district data is tabulated using individual income tax returns (Forms 1040) filed with the Internal Revenue Service (IRS) during the 12-month period, January 1, 2022 to December 31, 2022. While the bulk of returns filed during this 12-month period are primarily for Tax Year 2021, the IRS received a limited number of returns for tax years before 2021. These prior-year returns are used as a proxy for returns that are typically filed beyond the 12-month period and have been included within the congressional district data.


### Population Definitions and Tax Return Addresses

-   Congressional data are based on the population of individual income tax returns processed by the IRS during the 2022 calendar year.

-   Returns filed for the purpose of receiving an Economic Impact Payment, due to COVID-19, were excluded from the data.

-   State totals within the Congressional data may not be comparable to State totals published elsewhere by SOI because of disclosure protection procedures or the exclusion of returns that did not match based on the ZIP code. See footnote for complete State totals. [2] 

-   Data do not represent the full U.S. population because many individuals are not required to file an individual income tax return.

-   The address shown on the tax return may differ from the taxpayer’s actual residence.

-   Congressional districts were based on the ZIP code shown on the return.

-   Tax returns filed without a ZIP code and returns filed with a ZIP code that did not match the State code shown on the return were excluded.

-   Tax returns filed using Army Post Office (APO) and Fleet Post Office addresses, foreign addresses, and addresses in Puerto Rico, Guam, Virgin Islands, American Samoa, Marshall Islands, Northern Marianas, and Palau were excluded.


### Congressional District and ZIP Code Matching Procedures

SOI uses a commercial file to match ZIP codes to congressional districts. Congressional districts cover the 435 congressional districts in the 50 states and the District of Columbia. District boundaries are based on the 117th Congress.

The matching process first utilizes the 9-digit ZIP code, if present on the return, to determine the proper congressional district for that return. Nearly 97 percent of the returns match on the 9-digit ZIP code. When the 9-digit ZIP code is not available, the matching process uses the 5-digit ZIP code to determine the proper congressional district. Returns that do not match on ZIP code, or where a ZIP code is not present, are excluded from the data. 

Eight states (AK, DC, DE, MT, ND, SD, VT, and WY) have only one congressional district, therefore the matching procedures are not performed on these states. Returns with only one congressional district represent 2 percent of the total number of returns.

### Disclosure Protection Procedures

SOI did not attempt to correct any ZIP codes listed on the tax returns; however, it did take the following precautions to avoid disclosing information about specific taxpayers:

-   Income and tax items with less than 20 returns for a particular AGI class were combined with another AGI class within the same congressional district.  Collapsed AGI classes are identified with a double asterisk (**) in the Excel files.

-   Income and tax items with less than 20 returns for a congressional district were excluded.

-   If an income or tax item from one return constitutes more than a specified percentage of the total of any particular cell, the specific data item for that return is excluded from that cell.  For example, if the amount for wages from one return represents 75 percent of the value of the total for that cell, the data item will be suppressed. The actual threshold percentage used cannot be released.   

## Comments on the data

... Determining which records are CD records...
