---
output: html_document
editor_options: 
 chunk_output_type: console
---

# Introduction

Get data for area targeting:

-   States (to come)

-   Congressional districts (in progress)

Note that each qmd file has its own setup section in which it loads packages and constants. This is unnecessary duplication when rendering the entire project, but it is useful during development because it allows rendering individual qmd files without rendering the entire project.

## Notes, TODOs, discussion items

### Investigate collapsed AGI ranges in the SOI data

-   Per IRS documentation: "Income and tax items with less than 20 returns for a particular AGI class were combined with another AGI class within the same congressional district. Collapsed AGI classes are identified with a double asterisk (dropped) in the Excel files." **This will require attention soon.**

### Defining number of returns with AGI

-   We have an issue with AGI: for Congressional Districts IRS does NOT report the number of returns with AGI. They report two variables that should be close in concept: N1 (Number of returns), and N02650 (Number of returns with total income). For all CDs in the U.S. N1 was 157,375,370 in 2021 and N02650 was 155,283,590. Since N1 is larger and is probably a better indicator of total number of filers, we'll use that as the number-of-returns counterpart to AGI (c00100). We address this late in the process because for most of the data development we try to keep the data faithful to what IRS reports and because the solution chosen here may be suboptimal and we may want to change it later.

### What to push to GitHub

-   File sizes, GitHub limits, and file types (e.g., binary instead of csv). To discuss.

-   Web page - should we include it in GitHub? Discuss with Martin. Probably yes.

### Census population

Used to create the row 0 "XTOT" (population) target as a way to develop an initial scaling ratio:  `initial_weights_scale = row.target / national_population`.

-   Project currently uses 2021 population by Congressional District obtained from 1-year ACS via R package tidycensus. tidycensus reports that these are from the 116th Congressional session, not 117th (as I had expected). Seems like they must be appropriate, but requires verification.

-   2021 was a strange year for population data because of Covid. It might be better to use the 5-year ACS ending in 2021 for more stable and representative data.

