"""
Per-area solver override management.

Provides a centralized mechanism for storing and loading per-area
solver parameter overrides. The override file is a YAML file with
a ``_defaults`` section and per-area entries.

Developer mode generates this file by running iterative LP/QP
feasibility checks and applying a relaxation cascade. Production
mode reads it to configure each area's solve in a single pass.

File format::

    # Solver overrides for CDs
    _defaults:
      multiplier_max: 50
      constraint_tol: 0.005

    # Only areas needing special treatment appear below
    fl28:
      drop_targets:
        - "e26270/cnt=0/agi=[10000.0,25000.0)"
    ny12:
      constraint_tol: 0.01
      drop_targets:
        - "e00300/cnt=0/agi=[-9e+99,1.0)"
"""

from pathlib import Path
from typing import Dict, List

import yaml


def load_overrides(override_path: Path) -> dict:
    """
    Load solver overrides from a YAML file.

    Returns a dict with ``_defaults`` and per-area entries.
    If the file doesn't exist, returns empty defaults.
    """
    if not override_path.exists():
        return {"_defaults": {}}
    with open(override_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f.read())
    if data is None:
        data = {}
    if "_defaults" not in data:
        data["_defaults"] = {}
    return data


def get_area_overrides(
    overrides: dict,
    area: str,
) -> dict:
    """
    Get merged overrides for a specific area.

    Returns defaults updated with any area-specific overrides.
    Per-area values take precedence over defaults.
    """
    defaults = dict(overrides.get("_defaults", {}))
    area_specific = overrides.get(area, {})
    if area_specific:
        defaults.update(area_specific)
    return defaults


def get_drop_targets(overrides: dict, area: str) -> List[str]:
    """
    Get list of target labels to drop for an area.

    Returns a list of constraint label patterns to exclude
    from the QP. Empty list if no drops needed.
    """
    area_ovr = get_area_overrides(overrides, area)
    return area_ovr.get("drop_targets", [])


def should_drop_target(
    label: str,
    drop_patterns: List[str],
) -> bool:
    """
    Check if a target label matches any drop pattern.

    Patterns are matched as substrings of the full label.
    For example, "e26270/cnt=0/agi=[10000.0,25000.0)" matches
    any label containing that string.
    """
    for pattern in drop_patterns:
        if pattern in label:
            return True
    return False


def write_overrides(
    override_path: Path,
    defaults: dict,
    area_overrides: Dict[str, dict],
):
    """
    Write solver overrides to a YAML file.

    Parameters
    ----------
    override_path : Path
        Output file path.
    defaults : dict
        Default parameters for all areas.
    area_overrides : dict
        Per-area overrides (only areas needing special treatment).
    """
    data = {"_defaults": defaults}
    for area in sorted(area_overrides.keys()):
        ovr = area_overrides[area]
        if ovr:  # skip empty overrides
            data[area] = ovr

    override_path.parent.mkdir(parents=True, exist_ok=True)
    with open(override_path, "w", encoding="utf-8") as f:
        # Write header comment
        f.write("# Solver overrides — auto-generated by developer mode\n")
        f.write(
            "# Edit manually only if automatic relaxation is insufficient\n"
        )
        f.write("\n")
        yaml.dump(
            data,
            f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
