project:
  type: book
  execute-dir: project  

execute:
  eval: true
  echo: true
  output: true
  freeze: false  # auto: during global project renders, re-render only when source changes

book:
  title: "Get IRS data for possible use as PUF targets"
  subtitle: "Create csv file"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - prepare.qmd
    - examine.qmd

format:
  html:
    theme: cosmo
    code-fold: true    

editor_options:
  chunk_output_type: console


# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

# use qstop shortcut for this
# ```{r stop_here, echo=FALSE}
# knitr::knit_exit()
# ```
  
  