from pathlib import Path

STORAGE_FOLDER = Path(__file__).parent

# Growth factors used to index Policy parameters (as distinct from
# tmd_growfactors.csv, which extrapolates Records variables).  This file
# is created in the first stage of the `make tmd_files` pipeline.
POLICY_GROWFACTORS_PATH = STORAGE_FOLDER / "output" / "growfactors.csv"

# Paths of the files generated by the `make tmd_files` pipeline.
TMD_VARIABLES_PATH = STORAGE_FOLDER / "output" / "tmd.csv.gz"
TMD_WEIGHTS_PATH = STORAGE_FOLDER / "output" / "tmd_weights.csv.gz"
TMD_GROWFACTORS_PATH = STORAGE_FOLDER / "output" / "tmd_growfactors.csv"

CACHED_TAXCALC_VARIABLES = [
    "c00100",  # AGI
    "iitax",  # individual income tax liability (including refundable credits)
]
