---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Compare selected tmd sums and SOI vars

```{r}
#| label: setup
#| output: false

suppressPackageStartupMessages(source(here::here("R", "libraries.R")))
source(here::here("R", "constants.R"))
source(here::here("R", "functions.R"))

```


## Get data

```{r}
#| label: get-data
#| output: false

agilabels <- read_csv(fs::path(DINTERMEDIATE, "agilabels.csv"))
agilabels

fpath <-  fs::path(TMDDATA, "cached_allvars.csv")
tmd2021 <- vroom(fpath)
ns(tmd2021)

base_targets <- read_csv(fs::path(DINTERMEDIATE, "base_targets.csv"))
glimpse(base_targets)
# tmp <- count(base_targets, soivname, basesoivname, description)

```



## tmd sums


```{r}
#| label: get-tmdsums
#| output: false

tmdvars <- c("c00100", "e00200", "e00300",  "e01500",  "e01700", "e02400")

tmdsums1 <- tmd2021 |> 
  filter(data_source==1) |> 
  select(s006, all_of(tmdvars)) |> 
  pivot_longer(-c(s006),
               names_to = "tmdvar") |> 
  summarize(nzcount=sum(s006 * (value !=0)),
            amount=sum(s006 * value),
            .by=tmdvar) |> 
  arrange(tmdvar)

tmdsums1 |> 
  kable(format.args=list(big.mark=",", digits=13))

# E01500 Total pensions and annuities received
# E01700 Pensions and annuities included in AGI

# pensions
#   SOI taxable: 853,473,354,000
#   tmd taxable  858,205,915,983.9
#   tmd total  1,508,287,559,037.2

```


