---
output: html_document
editor_options: 
 chunk_output_type: console
---


## Setup

```{r}
#| label: setup

source(here::here("R", "libraries.R"))
source(here::here("R", "constants.R"))
source(here::here("R", "functions.R"))

```


## Create and save AGI bin labels, and show bins

Create and map AGI bin labels to the AGI bins that SOI uses, and save in ".../cds/raw".

```{r}
#| label: agi-bins
#| output: false

# in_bin = (vardf.c00100 >= row.agilo) & (vardf.c00100 < row.agihi)

agilabels <- read_delim(
delim=";",
trim_ws = TRUE,
file="agistub; agilo; agihi; agilabel
0; -9e99; 9e99; Total
1; -9e99; 1; Under $1
2; 1; 10e3; $1 under $10,000
3; 10e3; 25e3; $10,000 under $25,000
4; 25e3; 50e3; $25,000 under $50,000
5; 50e3; 75e3; $50,000 under $75,000
6; 75e3; 100e3; $75,000 under $100,000
7; 100e3; 200e3; $100,000 under $200,000
8; 200e3; 500e3; $200,000 under $500,000
9; 500e3; 9e99; $500,000 or more
")

write_csv(agilabels, fs::path(CDRAW, "agilabels.csv"))

```


Show AGI bins.

```{r}
#| label: show-agilabels

# agilabels |> kable()
agilabels |> 
  gt() |> 
  tab_header(
    title = html("Congressional District AGI bins"),
    subtitle = html("in_bin = (vardf.c00100 >= row.agilo) & (vardf.c00100 < row.agihi)")) |>
  fmt_number(columns=c(agilo, agihi),
             rows=3:9,
             # scale=1e-9,
             decimals=0)

```



